version: '3'

services:
    memcached:
        image: memcached:alpine

    postgres:
        image: mdillon/postgis
        environment:
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password123}"
        ports:
            - '5432:5432'

    server:
        build: ./
        links:
           - postgres
        environment:
           - GUNICORN_WORKERS=2
           - GUNICORN_BIND=unix:/socks/gunicorn.sock
        volumes:
            - socks:/socks
            - static_files:/var/www/dp_server/assets

    nginx:
        image: nginx:alpine
        ports:
            - 8000:80
            - 8443:443
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - static_files:/var/www/dp_server/assets
            - socks:/socks
volumes:
    socks:
    static_files: