version: '3'

services:

  letsencrypt:
    links:
      - nginx
    volumes:
      - certs:/etc/nginx/ssl
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt:/var/www
    environment:
      - EMAIL=fraser@doctorpricer.co.nz
      - SERVER_CONTAINER=nginx
      - WEBROOT_PATH=/tmp/letsencrypt/www
      - CERTS_PATH=/etc/nginx/ssl
      - DOMAINS=api.doctorpricer.co.nz
      - CHECK_FREQ=7
    restart: unless-stopped

volumes:
  certs: