version: '3'

services:

  # Memcached for Django
  memcached:
    image: memcached:alpine

  # Rabbit for Celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Postgres for our database
  postgres:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432'
    restart: always

  # Django
  server:
    image: fraserthompson/doctorpricerscrapers
    command: /run_server.sh
    environment:
      - ENV=${ENV:-staging}
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - SECRET_KEY
      - DATABASE_PASSWORD
    volumes:
      - socks:/socks
      - static_files:/var/www/dp_server/assets  
    depends_on:
      - postgres
    restart: always

  # Celery worker
  worker:
    image: fraserthompson/doctorpricerscrapers
    command: /run_celery.sh
    environment:
      - ENV=${ENV:-staging}
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - SECRET_KEY
      - DATABASE_PASSWORD
    depends_on:
      - rabbit
    restart: always

  # Nginx sits in front
  nginx:
    image: fraserthompson/doctorpricernginx
    ports:
      - 8443:443
      - 8000:80
    volumes:
      - socks:/socks
      - static_files:/var/www/dp_server/assets
    restart: always

volumes:
  socks:
  static_files: