version: '3'

services:
    nginx:
        build: ../dp_nginx
        restart: "no"

    server:
        build: ../dp_scrapers
        volumes:
            - ./dp_server:/var/www/dp_server
            - ./scrapers:/var/www/scrapers
        restart: "no"

    worker:
        build: ../dp_scrapers
        restart: "no"