version: '3'

services:
    memcached:
        image: memcached:alpine

    postgres:
        image: mdillon/postgis
        environment:
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password123}"
        ports:
            - '5432:5432'

    server:
        build: ./
        links:
           - postgres
        ports:
            - '8000:8000'
        volumes:
            - ./dp_server:/code/dp_server
            - ./scrapers:/code/scrapers