version: '3'

services:

  # Memcached for Django
  memcached:
    image: memcached:1.6.15-alpine

  # Rabbit for Celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.10.5
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Postgres for our database
  postgres:
    image: postgis/postgis:13-3.2-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432'
    restart: always
    volumes:
      - 'database:/var/lib/postgresql/data'

  # Django
  django:
    image: fraserthompson/doctorpricerscrapers
    command: /run_server.sh
    environment:
      - ENV=${ENV:-dev}
      - ADMIN_USER=fraser
      - RABBITMQ_DEFAULT_USER=rabbituser
      - ADMIN_PASSWORD
      - RABBITMQ_DEFAULT_PASS
      - SECRET_KEY
      - DATABASE_PASSWORD
      - GEOLOCATION_API_KEY
    volumes:
      - migrations:/var/www/dp_server/migrations
      - socks:/run/django
      - static_files:/var/www/dp_server/assets  
    depends_on:
      - postgres
    restart: always

  # Celery worker
  worker:
    image: fraserthompson/doctorpricerscrapers
    command: /run_celery.sh
    environment:
      - ENV=${ENV:-dev}
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS
      - SECRET_KEY
      - DATABASE_PASSWORD
      - GEOLOCATION_API_KEY
    depends_on:
      - rabbit
    restart: always

  # Nginx sits in front
  nginx:
    image: fraserthompson/doctorpricernginx
    environment:
      - ENV=${ENV:-dev}
    ports:
      - 443:443
      - 80:80
    volumes:
      - socks:/run/django
      - static_files:/var/www/dp_server/assets
      - nginx-certs:/etc/letsencrypt

volumes:
  socks:
  static_files:
  nginx-certs:
  database:
  migrations: