version: '3'

services: 
  backup:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password123}
      - PGPASSWORD=${DATABASE_PASSWORD:-password123}
    restart: "no"
    command: /bin/sh -c "pg_dump --dbname=postgres --username=postgres --host=postgres -Fc --compress=5 > /backups/backup.tar.gz"
    volumes:
      - ./backups:/backups
  
  restore:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password123}
      - PGPASSWORD=${DATABASE_PASSWORD:-password123}
    restart: "no"
    depends_on:
      - postgres
    command: /bin/sh -c "pg_restore --dbname=postgres --username=postgres --host=postgres /backups/backup.tar.gz"
    volumes:
      - ./backups:/backups

  postgres:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432'
    restart: always
    volumes:
      - 'database:/var/lib/postgresql/data'

volumes:
  database: