version: '3'

services:

  backup:
    command: "/bin/sh -c 'pg_dump --dbname=postgres --username=postgres --host=postgres -Fc > /backups/backup.tar.gz'"
    environment:
      - PGPASSWORD=${DATABASE_PASSWORD:-password123}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password123}
    image: mdillon/postgis:10-alpine
    restart: "no"
    volumes:
      - ~/backups:/backups
  
  restore:
    command: /bin/sh -c "pg_restore --dbname=postgres --username=postgres --host=postgres /backups/backup.tar.gz"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password123}
      - PGPASSWORD=${DATABASE_PASSWORD:-password123}
    image: mdillon/postgis:10-alpine
    restart: "no"
    depends_on:
      - postgres
    volumes:
      - ~/restore:/backups

  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432'
    restart: always
    volumes:
      - 'database:/var/lib/postgresql/data'

volumes:
  database: