version: '3'

services:
    nginx:
        build: ../dp_nginx
        restart: "no"
        ports:
            - 8443:443
            - 8000:80

    postgres:
        environment:
            - POSTGRES_PASSWORD=password123

    django:
        build: ../dp_scrapers
        environment:
            - ADMIN_PASSWORD=dev
            - ADMIN_USER=fraserdev
            - DATABASE_PASSWORD=password123
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypass
            - SECRET_KEY=hugesecretdontsharewithanyone
        volumes:
            - ./dp_server:/var/www/dp_server
            - ./scrapers:/var/www/scrapers
        restart: "no"

    worker:
        build: ../dp_scrapers
        restart: "no"
        environment:
            - DATABASE_PASSWORD=password123
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypass
            - SECRET_KEY=hugesecretdontsharewithanyone

    rabbit:
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypass

    scraper-test:
        build: ./scrapers
        environment:
            - GEOLOCATION_API_KEY
        volumes:
            - ./scrapers:/scrapers:rw