version: '3'

services:
    memcached:
        image: memcached:alpine

    postgres:
        image: mdillon/postgis
        environment:
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password123}"
        ports:
            - '5432'
        restart: always

    server:
        build: fraserthompson/doctorpricerscrapers
        links:
           - postgres
        environment:
           - GUNICORN_WORKERS=2
           - GUNICORN_BIND=unix:/socks/gunicorn.sock
           - ENV=${ENV:-staging}
        volumes:
            - socks:/socks
            - static_files:/var/www/dp_server/assets
        restart: always

    nginx:
        image: fraserthompson/doctorpricernginx
        ports:
            - 8443:443
            - 8000:80
        volumes:
            - ./conf/ssl:/etc/nginx/ssl:ro
            - static_files:/var/www/dp_server/assets
            - socks:/socks
        restart: always

volumes:
    socks:
    static_files: